export const POSTHOG_EVENTS = {
  authSignUpSubmitted: 'auth_sign_up_submitted',
  authSignUpCompleted: 'auth_sign_up_completed',
  authLoginCompleted: 'auth_login_completed',
  authMagicLinkRequested: 'auth_magic_link_requested',
  authSignOut: 'auth_sign_out',
  onboardingStarted: 'onboarding_started',
  onboardingSkipped: 'onboarding_skipped',
  onboardingCompleted: 'onboarding_completed',
  onboardingStepViewed: 'onboarding_step_viewed',
  onboardingStepCompleted: 'onboarding_step_completed',
  onboardingChecklistItemClicked: 'onboarding_checklist_item_clicked',
  onboardingHintViewed: 'onboarding_hint_viewed',
  onboardingHintDismissed: 'onboarding_hint_dismissed',
  onboardingReplayed: 'onboarding_replayed',
  emptyStateCtaClicked: 'empty_state_cta_clicked',
  tooltipOpened: 'tooltip_opened',
  timeToFirstSnapshot: 'time_to_first_snapshot',
  timeToFirstRateCard: 'time_to_first_rate_card',
  timeToFirstDeal: 'time_to_first_deal',
  firstAiNegotiationMessage: 'first_ai_negotiation_message',
  firstChannelAdvisorMessage: 'first_channel_advisor_message',
  analyticsUploadStarted: 'analytics_snapshot_upload_started',
  analyticsUploadValidationFailed: 'analytics_snapshot_upload_validation_failed',
  analyticsSnapshotCreated: 'analytics_snapshot_created',
  analyticsSnapshotViewed: 'analytics_snapshot_viewed',
  analyticsSnapshotDeleted: 'analytics_snapshot_deleted',
  rateCardGenerationStarted: 'rate_card_generation_started',
  rateCardGenerationSucceeded: 'rate_card_generation_succeeded',
  rateCardGenerationFailed: 'rate_card_generation_failed',
  rateCardViewed: 'rate_card_viewed',
  rateCardUsedToCreateDeal: 'rate_card_used_to_create_deal',
  dealCreated: 'deal_created',
  dealViewed: 'deal_viewed',
  dealStatusChanged: 'deal_status_changed',
  dealPricingUpdated: 'deal_pricing_updated',
  dealAnalyticsSnapshotChanged: 'deal_analytics_snapshot_changed',
  channelAiChatCreated: 'channel_ai_chat_created',
  channelAiMessageSent: 'channel_ai_message_sent',
  channelAiGenerationStopped: 'channel_ai_generation_stopped',
  channelAiChatRenamed: 'channel_ai_chat_renamed',
  channelAiChatDeleted: 'channel_ai_chat_deleted',
  channelAiSnapshotSwitched: 'channel_ai_snapshot_switched',
  negotiationChatCreated: 'negotiation_chat_created',
  negotiationMessageSent: 'negotiation_message_sent',
  negotiationGenerationStopped: 'negotiation_generation_stopped',
  negotiationBrandOfferDetected: 'negotiation_brand_offer_detected',
  negotiationCreatorAskDetected: 'negotiation_creator_ask_detected',
  negotiationSuggestedScriptGenerated: 'negotiation_suggested_script_generated',
  aiRequestStarted: 'ai_request_started',
  aiRequestCompleted: 'ai_request_completed',
  aiRequestFailed: 'ai_request_failed',
  aiRequestRateLimited: 'ai_request_rate_limited',
  aiRequestAborted: 'ai_request_aborted',
  feedbackSubmitted: 'feedback_submitted',
} as const

export type PostHogEventName = (typeof POSTHOG_EVENTS)[keyof typeof POSTHOG_EVENTS]

export type AnalyticsEventProperties = Record<string, string | number | boolean | null | undefined>
